# docker-compose.yml
version: "3"

services:
  mongo:
    image: mongo
    container_name: mongo-kvr
    environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27017:27017"
    volumes:
      - ./database/mongo:/data/db
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    container_name: mongoexpress-kvr
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_URL=mongodb://root:root@mongo:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=root
    links:
      - mongo
    ports:
      - "9000:8081"
    restart: unless-stopped
